container_image = docker://edward829/r-simulation:latest
universe = container

executable = run_mxkf.sh
arguments = $(p) $(pos) $(u) $(fdr)

transfer_input_files = run_mxkf.sh,  mxkf_complete_serial.R, count.Rdata

log = mxkf_complete_$(p)_$(pos)_$(u)_$(fdr).log
error = mxkf_complete_$(p)_$(pos)_$(u)_$(fdr).err
output = mxkf_complete_$(p)_$(pos)_$(u)_$(fdr).out

request_cpus = 1
request_memory = 8GB
request_disk = 5GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

